on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: arduino-lint
        # You may pin to the exact commit or the version.
        uses: arduino/arduino-lint-action@v1
        with:
          # How strict the checks are.
          compliance: strict
          # Configuration of the checks for libraries in the Arduino Library Manager index.
          library-manager: update
          # The type of project to check.
          project-type: library # optional, default is all
          # Show more information on the checks being run.
          verbose: true # optional, default is false
